### PR TITLE
added dark theme

### PR DESCRIPTION
**Pull request by yashrajbharti**

### CODE REVIEW

**Comment by shivanshs9** [comment]
The script doesn't work in all the pages, including individual blog pages. Also can you save user's preference in local storage or something and use its value?

**Comment by yashrajbharti** [comment]
> The script doesn't work in all the pages, including individual blog pages. Also can you save user's preference in local storage or something and use its value?

i saw that the link changes to copsiitbhu.co.in on blog pages and dev extravaganza, although it wasn't the case in my local and the blog pages were too shown it dark theme, 

please see if the deploy preview is redirecting.. 

For sure it will get fixed if changes come to the copsiitbhu.co.in site as well.

**Comment by yashrajbharti** [comment]
Enhanced theme.js file with local storage and timely theme switch so that if the time is after 6AM or before 7PM, apply day theme to ‘body’ else night theme. Local storage shall give user's preference  to use the theme of his choice.

**Comment by shivanshs9** [comment]
Yup, works well now!
For the placement, how about just a single moon/sun icon button in the app bar? For Desktop, we could have the button at the right end. And for mobile, we could remove the COPS(IIT BHU) text in app bar to make space for this icon.

**Comment by yashrajbharti** [comment]
Added back "Code of Conduct" and replaced the toggle button with🌤 and 🌑 SVG's so as to avoid any text like "switch theme" and this whole thing can come in a lot less space.

**Comment by shivanshs9** [comment]
Yup, it looks really cool! 🤟🏻
Just a tiny suggestion... Can you use the purple color used for header in appbar, for the selected moon icon?

**Comment by yashrajbharti** [comment]
so far so good

**Comment by shivanshs9** [comment]
LGTM! :+1:
Thanks for your contribution!

**Review by shivanshs9 — APPROVED** [review]

**Pull request merged**
