### PR TITLE
cops logo added (Issue #22)

### PR DESCRIPTION
**Pull request by manvendra09**
cops logo added in the header

### CODE REVIEW

**Comment by shivanshs9** [comment]
Thanks for your contributions! Hope you tested your work well.

Here's a couple of heads up! :+1: 
- Each PR should be linked with an issue, either in title or description. For now, I've linked this PR with the appropriate issue.
- I like how you went about implementing it, but the logo which is used can be improved. We had a different logo in mind, and would've loved to share thoughts on it with those who would have shown interest in the issue #22 itself. So, make sure to first discuss with the mentor who created the issue before directly creating a PR.

**Review by shivanshs9 — CHANGES_REQUESTED** [review]
Thanks for your contributions! Hope you tested your work well.

Here's a couple of heads up! :+1: 
- Each PR should be linked with an issue, either in title or description. For now, I've linked this PR with the appropriate issue.
- I like how you went about implementing it, but the logo which is used can be improved. We had a different logo in mind, and would've loved to share thoughts on it with those who would have shown interest in the issue #22 itself. So, make sure to first discuss with the mentor who created the issue before directly creating a PR.

**Comment by manvendra09** [comment]
i don't know who is my mentor..and how to contact him...

**Comment by shivanshs9** [comment]
It's mentioned in the rules to communicate in the issue regarding your
willingness to work on it. After that, a mentor would be alloted to you.

Thanks,
Shivansh Saini

**Pull request closed without merging**
