### PR TITLE
Modified Search Icon (Issue #27)

### PR DESCRIPTION
**Pull request by arron-tij**
Tried resolving issue #27 .

(The first 6 commits are not relevant to this issue and are being displayed since I didn't make a separate branch in the starting.)

### CODE REVIEW

**Comment by pegasus-lynx** [comment]
@arron-tij have you read the guidelines of the task before contributing to the project? 
I am referring to this [CSOC-Dev Week 4](https://github.com/COPS-IITBHU/csoc-dev-week4)

**Comment by arron-tij** [comment]
> @arron-tij have you read the guidelines of the task before contributing to the project?
> I am referring to this [CSOC-Dev Week 4](https://github.com/COPS-IITBHU/csoc-dev-week4)

Well the README has been changed I think. Those points were not there when i made these PRs.  How do I get assigned?. I have already made PR's to some , but according to new guidelines can I be assigned #19 #21 #26 . I have already commented on the #19 #21 . Can I be assigned those?

**Comment by pegasus-lynx** [comment]
Yes, the last two points were missing because we had in mind that participants would first comment in the issue they would like to work on and then only we would assign them and then the person would start working ( although the points about assigning were mentioned ).
This is the natural flow, of how we contribute to others project. 
So in order to make things evident we added those extra rules.
Certainly, in bigger organizations where there are hundreds of issues, so the maintainers prefer to have a discussion over the topic before going on with the implementation.

And about the irrelevant commits, it seems like you made the changes directly via GitHub. That's not a way to contribute to any project. It is preferable to set up the project locally and test the changes before making a commit. And then when you are satisfied stage all your changes and commit them at as one commit.

I'd suggest you make a new branch from the latest master (not your master) and commit all your changes there before pushing to your PR and making a new PR.

**Comment by arron-tij** [comment]
> Yes, the last two points were missing because we had in mind that participants would first comment in the issue they would like to work on and then only we would assign them and then the person would start working ( although the points about assigning were mentioned ).
> This is the natural flow, of how we contribute to others project.
> So in order to make things evident we added those extra rules.
> Certainly, in bigger organizations where there are hundreds of issues, so the maintainers prefer to have a discussion over the topic before going on with the implementation.
> 
> And about the irrelevant commits, it seems like you made the changes directly via GitHub. That's not a way to contribute to any project. It is preferable to set up the project locally and test the changes before making a commit. And then when you are satisfied stage all your changes and commit them at as one commit.
> 
> I'd suggest you make a new branch from the latest master (not your master) and commit all your changes there before pushing to your PR and making a new PR.

I didn't know how to set up a local environment for this backend so I instead deployed my forked repo on netlify and hence I used to make changes in my repo and then preview the deploy. Is that wrong?

**Comment by pegasus-lynx** [comment]
> > @arron-tij have you read the guidelines of the task before contributing to the project?
> > I am referring to this [CSOC-Dev Week 4](https://github.com/COPS-IITBHU/csoc-dev-week4)
> 
> Well the README has been changed I think. Those points were not there when i made these PRs. How do I get assigned?. I have already made PR's to some , but according to new guidelines can I be assigned #19 #21 #26 . I have already commented on the #19 #21 . Can I be assigned those?

Please leave a comment on the issue you would like to work on. Moreover, you have made multiple commits for resolving each issue, which I made clear in the last comment that it won't be accepted.

**Comment by arron-tij** [comment]
Can you please preview the deploy of the fix in this PR which I tried making for the search icon issue. If it is correct then I will make separate commit for it .

**Comment by pegasus-lynx** [comment]
> > Yes, the last two points were missing because we had in mind that participants would first comment in the issue they would like to work on and then only we would assign them and then the person would start working ( although the points about assigning were mentioned ).
> > This is the natural flow, of how we contribute to others project.
> > So in order to make things evident we added those extra rules.
> > Certainly, in bigger organizations where there are hundreds of issues, so the maintainers prefer to have a discussion over the topic before going on with the implementation.
> > And about the irrelevant commits, it seems like you made the changes directly via GitHub. That's not a way to contribute to any project. It is preferable to set up the project locally and test the changes before making a commit. And then when you are satisfied stage all your changes and commit them at as one commit.
> > I'd suggest you make a new branch from the latest master (not your master) and commit all your changes there before pushing to your PR and making a new PR.
> 
> I didn't know how to set up a local environment for this backend so I instead deployed my forked repo on netlify and hence I used to make changes in my repo and then preview the deploy. Is that wrong?

Yes, it is wrong. In our case, we have a netlify where you can preview deploy but in any general case, you won't have such facilities.

**Comment by pegasus-lynx** [comment]
> Can you please preview the deploy of the fix in this PR which I tried making for the search icon issue. If it is correct then I will make separate commit for it .

Yes, I reviewed your PR. There were some points I would like to mention 

- The colour doesn't match. 
- Reduce the size of icon ( the white icon only ).

**Comment by arron-tij** [comment]
> > Can you please preview the deploy of the fix in this PR which I tried making for the search icon issue. If it is correct then I will make separate commit for it .
> 
> Yes, I reviewed your PR. There were some points I would like to mention
> 
> * The colour doesn't match.
> * Reduce the size of icon ( the white icon only ).

Ok I will find the exact hex value and reduce the size and make a separate commit. As for now I will post a comment in the issue asking for it to be assigned to me.

**Pull request closed without merging**
