### PR TITLE
Tried to resolve Issue #21 and #20

### PR DESCRIPTION
**Pull request by arron-tij**
Changed the POTW link from the timeline section as a solution to Issue #21 and Issue #20 

Also changed the link to POTW page in Projects section

### CODE REVIEW

**Comment by shivanshs9** [comment]
Thanks for your contribution! Hope you checked out your Netlify-built deploy preview too.
Just a few heads-up! :+1: 
- Use relative links with respect to root, rather than writing the link directly. Otherwise the site can't be used to test in a testing environment.
- Try to avoid working on the master branch, but rather create a new branch from the master where you'll code on solving the issue.

**Comment by arron-tij** [comment]
I will keep those points in mind. I used the direct link because the POTW doc link also seemed direct. And yes I have created a Netlify deploy of my forked repository to preview changes as i make them. I wanted to ask should i make a separate branch for every issue I try to resolve?
Because I tried resolving issue #20 and it got merged in this PR itself.

**Comment by pegasus-lynx** [comment]
There is a problem with the #20 fix. In order to bring the menu options in the same line, you have shifted the homepage link to the left margin. The position of the homepage link should remain the same.

**Comment by arron-tij** [comment]
> There is a problem with the #20 fix. In order to bring the menu options in the same line, you have shifted the homepage link to the left margin. The position of the homepage link should remain the same.

Can I then shift it just a bit to left only when the viewport size decreases?

**Pull request closed without merging**
