### PR TITLE
Trial demo for CSOC Leaderboard (Fixes #28)

### LINKED ISSUE #28: CSOC Leaderboard
CSOC Leaderboard section needs to be added in the CSOC page.
The structure of the leaderboard should be similar to that of the POTW page - 

- should have three dropdown lists (one for each ML, Dev, CP )
- each list should display a table listing the name, institute, and points of the participants.

### PR DESCRIPTION
**Pull request by arron-tij**
This is just a trial idea for Issue #28 . Please tell me if this is what the issue required and what more should I add. I will make a better one based on reviews and close this PR and create a new PR (and also make it in one commit). Other than that what else should I do.

### CODE REVIEW

**Review by shivanshs9 — CHANGES_REQUESTED** [review]
Nice work in using Jekyll data yamls! The leaderboard looks neat. My only request is to move it down after timeline.

**Comment by arron-tij** [comment]
I think I made lot of commits which I am not able to squash into one. I need to make a new PR now don't I ? Although I think the last commit in the list is a squash of all previous.

**Comment by shivanshs9** [comment]
After squashing the commits, do a force push on this branch to update this PR.

**Comment by arron-tij** [comment]
Done

**Comment by shivanshs9** [comment]
Stale PR.

**Pull request closed without merging**
