### PR TITLE
Changed Alignment Of Description ( Issue #24)

### PR DESCRIPTION
**Pull request by nishantwrp**
Resolved Issue #24

### CODE REVIEW

**Comment by shivanshs9** [comment]
Thanks for your contributions! Hope you tested your work well.

Here's a couple of heads up! :+1: 
- The issue was meant to solve in the CSOC page.
- The justify alignment is actually not applied by the change you did. It can be seen from the deploy preview.

**Comment by nishantwrp** [comment]
The Justify Alignment is working , you can see the diff b/w original website and the deploy preview
img2
img1

**Comment by pegasus-lynx** [comment]
@nishantwrp you had to change the alignment of the description on CSOC page. The screenshot you have attached is of the homepage of the website.

**Comment by nishantwrp** [comment]
@pegasus-lynx Ohhk. I have made the required changes

**Comment by pegasus-lynx** [comment]
Thanks for your contribution!  This looks alright to me. :+1:

**Comment by shivanshs9** [comment]
@nishantwrp I can see you have made two more commits to fix your previous work. Also, you did changes and commited directly via Github. That's not a way to contribute in any project. You need to first setup a local development environment, do changes locally, stage all the changes and commit them as one commit, before making a PR.

I'd suggest you to make a new branch from the latest master (not your master) and commit all your changes there before pushing to your PR and making a new PR.

**Comment by nishantwrp** [comment]
@shivanshs9  There were not many changes required to fix this bug, only addition of a word. So, I used github itself for making changes.

**Comment by shivanshs9** [comment]
Then do one thing. Squash all the 3 commits into one.

**Comment by nishantwrp** [comment]
@shivanshs9 I don't know how to do that , I think one who can merge pull request can only do that.

**Comment by shivanshs9** [comment]
You can interactively rebase your work and force push it. Try out this blog
-
https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/

**Comment by nishantwrp** [comment]
@shivanshs9 Done :)

**Comment by shivanshs9** [comment]
LGTM! :100:

**Pull request merged**
