### PR TITLE
Display toggle button only in chrome based browsers

### LINKED ISSUE #61: The light/dark mode toggle button does show not correctly
Screenshot_20191203_172205

### PR DESCRIPTION
**Pull request by nishantwrp**
Try to fix #61 completely by not showing the toggle button in other browsers like firefox

### CODE REVIEW

**Comment by nishantwrp** [comment]
@shivanshs9,
This is working fine as a fix locally for me but still, the toggle button is showing up in the deploy preview in firefox. Any ideas why this might be happening?

I referred this https://stackoverflow.com/questions/32141052/hide-element-on-firefox-ie-and-show-only-on-chrome

**Comment by shivanshs9** [comment]
Why not use JS for it?
https://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browser

**Comment by nishantwrp** [comment]
Yes, I can try using JS for this but how is this working fine locally and not in production?

________________________________

**Comment by nishantwrp** [comment]
@shivanshs9 PTAL!

**Comment by shivanshs9** [comment]
LGTM! 🤘🏻

**Pull request merged**
